name: WJL Pull-Request Reviews

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=20 --max-line-length=127 --statistics --exclude=app/__init__.py,venv/*,cypress-testing/* --ignore=E712,E711,W503,W504
      - name: Set up npm
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: UI Test with cypress
        uses: cypress-io/github-action@v2
        with:
          start: coverage run runserver.py
          wait-on: "http://localhost:5000"
          working-directory: cypress-testing
          record: false
          command: npm run test:all
        env:
          ARE_TESTING: true
      - name: Upload Video Run
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: cypress-videos
          path: cypress-testing/cypress/videos
      - name: Generate Code Coverage Report
        run: |
          coverage xml -o e2e.xml
      - name: Upload Cypress code coverage
        uses: codecov/codecov-action@v1
        with:
          flags: e2e # optional
          name: testing
          files: e2e.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
