name: WJL Pull-Request Reviews

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=20 --max-line-length=127 --statistics --exclude=app/__init__.py,venv/*,cypress-testing/* --ignore=E712,E711,W503,W504
      - name: Set up npm
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: UI Test with cypress
        run: |
          export ARE_TESTING=true
          # run the server just in-memory
          nohup python runserver.py  2>&1 &
          # now run the cypres tests against it
          cd cypress-testing
          npm install
          npm run checkLint
          npm run test:all
      - name: Upload Video Run
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: cypress-videos
          path: cypress-testing/cypress/videos
